version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./test.db
      - SECRET_KEY=your-production-secret-key-change-this
    volumes:
      - .:/app